      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: MaidaSyed
          file: profile/trophy.svg
          theme: algolia
          max-cols: 6
          margin-width: 10
          margin-height: 10
          no-frame: true
          token: ${{ secrets.TROPHY_TOKEN }}
